package com.example.data.repository

import com.example.data.local.ChapterEntity
import com.example.data.model.Subject

object InitialCurriculumData {

    val SUBJECTS = listOf(
        Subject(
            id = "math",
            name = "Mathematics",
            hindiName = "गणित",
            iconEmoji = "📐",
            colorHex = 0xFF2563EB,
            orderIndex = 1,
            description = "Algebra, Geometry, Trigonometry, Statistics & Probability"
        ),
        Subject(
            id = "science",
            name = "Science",
            hindiName = "विज्ञान",
            iconEmoji = "🔬",
            colorHex = 0xFF059669,
            orderIndex = 2,
            description = "Physics, Chemistry & Biology (NCERT + MP Board)"
        ),
        Subject(
            id = "sst",
            name = "Social Science",
            hindiName = "सामाजिक विज्ञान",
            iconEmoji = "🌍",
            colorHex = 0xFFD97706,
            orderIndex = 3,
            description = "History, Geography, Civics & Economics"
        ),
        Subject(
            id = "english",
            name = "English",
            hindiName = "अंग्रेजी",
            iconEmoji = "🇬🇧",
            colorHex = 0xFF7C3AED,
            orderIndex = 4,
            description = "First Flight, Footprints, Grammar & Writing"
        ),
        Subject(
            id = "hindi",
            name = "Hindi",
            hindiName = "हिंदी",
            iconEmoji = "🇮🇳",
            colorHex = 0xFFEA580C,
            orderIndex = 5,
            description = "क्षितिज, कृतिका, व्याकरण (रस, छंद, अलंकार)"
        ),
        Subject(
            id = "sanskrit",
            name = "Sanskrit",
            hindiName = "संस्कृत",
            iconEmoji = "🕉️",
            colorHex = 0xFF0D9488,
            orderIndex = 6,
            description = "शेमुषी भाग-2, सन्धि, समास, धातु रूप, शब्द रूप"
        )
    )

    fun getDefaultChapters(): List<ChapterEntity> {
        return listOf(
            // MATHEMATICS (MP Board Class 10 - NCERT rationalized)
            ChapterEntity(
                id = "math_ch1",
                subjectId = "math",
                chapterNumber = 1,
                titleEnglish = "Real Numbers",
                titleHindi = "वास्तविक संख्याएँ",
                subCategory = "Number Systems",
                isIncludedInMpBoard = true,
                orderIndex = 101,
                summaryHinglish = "Fundamental Theorem of Arithmetic states that every composite number can be uniquely factorized into primes. Proving √2, √3, √5 as irrational numbers by contradiction.",
                summaryHindi = "अंकगणित की आधारभूत प्रमेय के अनुसार प्रत्येक भाज्य संख्या को अभाज्य गुणनखंडों के गुणनफल के रूप में व्यक्त किया जा सकता है। √2, √3, √5 को अपरिमेय सिद्ध करना।",
                summaryEnglish = "Fundamental Theorem of Arithmetic and proving irrationality of square roots of primes by contradiction method.",
                ncertReference = "NCERT Class 10 Math Chapter 1"
            ),
            ChapterEntity(
                id = "math_ch2",
                subjectId = "math",
                chapterNumber = 2,
                titleEnglish = "Polynomials",
                titleHindi = "बहुपद",
                subCategory = "Algebra",
                isIncludedInMpBoard = true,
                orderIndex = 102,
                summaryHinglish = "Zeroes of quadratic polynomial ax² + bx + c. Sum of zeroes (α + β) = -b/a, Product of zeroes (αβ) = c/a.",
                summaryHindi = "द्विघात बहुपद के शून्यकों और गुणांकों के बीच संबंध: α + β = -b/a तथा αβ = c/a।",
                summaryEnglish = "Relationship between zeroes and coefficients of quadratic polynomials.",
                ncertReference = "NCERT Class 10 Math Chapter 2"
            ),
            ChapterEntity(
                id = "math_ch3",
                subjectId = "math",
                chapterNumber = 3,
                titleEnglish = "Pair of Linear Equations in Two Variables",
                titleHindi = "दो चरों वाले रैखिक समीकरण युग्म",
                subCategory = "Algebra",
                isIncludedInMpBoard = true,
                orderIndex = 103,
                summaryHinglish = "Solving pair of linear equations by Substitution, Elimination, and Graphical method. Consistency conditions: intersecting (unique), parallel (no solution), coincident (infinitely many).",
                summaryHindi = "दो चरों वाले रैखिक समीकरणों को हल करने की प्रतिस्थापन एवं विलोपन विधियाँ। संगत व असंगत समीकरण युग्म।",
                summaryEnglish = "Graphical and algebraic methods (Substitution, Elimination) to solve pairs of linear equations in two variables.",
                ncertReference = "NCERT Class 10 Math Chapter 3"
            ),
            ChapterEntity(
                id = "math_ch4",
                subjectId = "math",
                chapterNumber = 4,
                titleEnglish = "Quadratic Equations",
                titleHindi = "द्विघात समीकरण",
                subCategory = "Algebra",
                isIncludedInMpBoard = true,
                orderIndex = 104,
                summaryHinglish = "Standard form ax² + bx + c = 0 (a ≠ 0). Solving by factorization and quadratic formula x = (-b ± √(b² - 4ac)) / (2a). Discriminant D = b² - 4ac determines nature of roots.",
                summaryHindi = "द्विघात सूत्र x = [-b ± √(b² - 4ac)] / (2a)। विविक्तकर D = b² - 4ac द्वारा मूलों की प्रकृति की जांच।",
                summaryEnglish = "Standard form of quadratic equation, solution by factorization and quadratic formula, nature of roots via discriminant.",
                ncertReference = "NCERT Class 10 Math Chapter 4"
            ),
            ChapterEntity(
                id = "math_ch5",
                subjectId = "math",
                chapterNumber = 5,
                titleEnglish = "Arithmetic Progressions",
                titleHindi = "समान्तर श्रेढ़ी (AP)",
                subCategory = "Algebra",
                isIncludedInMpBoard = true,
                orderIndex = 105,
                summaryHinglish = "AP is a sequence with constant difference d. nth term an = a + (n - 1)d. Sum of first n terms Sn = n/2 [2a + (n - 1)d] or Sn = n/2 [a + l].",
                summaryHindi = "समान्तर श्रेढ़ी का nवाँ पद an = a + (n-1)d तथा प्रथम n पदों का योग Sn = n/2 [2a + (n-1)d]।",
                summaryEnglish = "Definition of AP, finding nth term and sum of first n terms with practical word problems.",
                ncertReference = "NCERT Class 10 Math Chapter 5"
            ),
            ChapterEntity(
                id = "math_ch6",
                subjectId = "math",
                chapterNumber = 6,
                titleEnglish = "Triangles",
                titleHindi = "त्रिभुज",
                subCategory = "Geometry",
                isIncludedInMpBoard = true,
                orderIndex = 106,
                summaryHinglish = "Basic Proportionality Theorem (Thales Theorem): If line drawn parallel to one side of triangle, it divides other two sides in same ratio. Similarity criteria: AAA, SSS, SAS.",
                summaryHindi = "आधारभूत आनुपातिकता प्रमेय (थेल्स प्रमेय) तथा त्रिभुजों की समरूपता की कसौटियाँ (AAA, SSS, SAS)।",
                summaryEnglish = "Basic Proportionality Theorem (BPT) and criteria for similarity of triangles.",
                ncertReference = "NCERT Class 10 Math Chapter 6"
            ),
            ChapterEntity(
                id = "math_ch7",
                subjectId = "math",
                chapterNumber = 7,
                titleEnglish = "Coordinate Geometry",
                titleHindi = "निर्देशांक ज्यामिति",
                subCategory = "Geometry",
                isIncludedInMpBoard = true,
                orderIndex = 107,
                summaryHinglish = "Distance formula d = √[(x2 - x1)² + (y2 - y1)²]. Section formula for internal division: P(x,y) = ((m1 x2 + m2 x1)/(m1 + m2), (m1 y2 + m2 y1)/(m1 + m2)). Midpoint formula.",
                summaryHindi = "दूरी सूत्र d = √[(x2-x1)² + (y2-y1)²] तथा विभाजन सूत्र। मध्य बिंदु के निर्देशांक।",
                summaryEnglish = "Distance formula and section formula for coordinates in Cartesian plane.",
                ncertReference = "NCERT Class 10 Math Chapter 7"
            ),
            ChapterEntity(
                id = "math_ch8",
                subjectId = "math",
                chapterNumber = 8,
                titleEnglish = "Introduction to Trigonometry",
                titleHindi = "त्रिकोणमिति का परिचय",
                subCategory = "Trigonometry",
                isIncludedInMpBoard = true,
                orderIndex = 108,
                summaryHinglish = "Ratios: sin θ = P/H, cos θ = B/H, tan θ = P/B. Values for 0°, 30°, 45°, 60°, 90°. Fundamental identity: sin²θ + cos²θ = 1, 1 + tan²θ = sec²θ.",
                summaryHindi = "त्रिकोणमितीय अनुपात, विशिष्ट कोणों (0°, 30°, 45°, 60°, 90°) के मान एवं सर्वसमिका sin²θ + cos²θ = 1।",
                summaryEnglish = "Trigonometric ratios of acute angles, standard angle values, and fundamental trigonometric identities.",
                ncertReference = "NCERT Class 10 Math Chapter 8"
            ),
            ChapterEntity(
                id = "math_ch9",
                subjectId = "math",
                chapterNumber = 9,
                titleEnglish = "Circles",
                titleHindi = "वृत्त",
                subCategory = "Geometry",
                isIncludedInMpBoard = true,
                orderIndex = 109,
                summaryHinglish = "Tangent to a circle is perpendicular to radius through point of contact. The lengths of tangents drawn from an external point to a circle are equal (PA = PB).",
                summaryHindi = "वृत्त के किसी बिंदु पर स्पर्श रेखा स्पर्श बिंदु से जाने वाली त्रिज्या पर लंब होती है। बाह्य बिंदु से खींची गई स्पर्श रेखाओं की लंबाइयाँ बराबर होती हैं।",
                summaryEnglish = "Tangents to circles, point of contact theorem, and equal tangent lengths from external points.",
                ncertReference = "NCERT Class 10 Math Chapter 10"
            ),
            ChapterEntity(
                id = "math_ch10",
                subjectId = "math",
                chapterNumber = 10,
                titleEnglish = "Statistics & Probability",
                titleHindi = "सांख्यिकी एवं प्रायिकता",
                subCategory = "Statistics",
                isIncludedInMpBoard = true,
                orderIndex = 110,
                summaryHinglish = "Mean (Direct method Σfi xi / Σfi), Mode of grouped data, Median. Probability P(E) = Number of favorable outcomes / Total outcomes. 0 ≤ P(E) ≤ 1.",
                summaryHindi = "वर्गीकृत आंकड़ों का माध्य, बहुलक, माध्यक। प्रायिकता P(E) = अनुकूल परिणाम / कुल परिणाम।",
                summaryEnglish = "Mean, median, mode of grouped data and classical probability calculations.",
                ncertReference = "NCERT Class 10 Math Chapters 13 & 14"
            ),

            // SCIENCE (MP Board Class 10)
            ChapterEntity(
                id = "sci_ch1",
                subjectId = "science",
                chapterNumber = 1,
                titleEnglish = "Chemical Reactions & Equations",
                titleHindi = "रासायनिक अभिक्रियाएँ एवं समीकरण",
                subCategory = "Chemistry",
                isIncludedInMpBoard = true,
                orderIndex = 201,
                summaryHinglish = "Balancing equations to obey Law of Conservation of Mass. Types: Combination, Decomposition, Displacement, Double Displacement, Redox (Oxidation & Reduction). Corrosion and Rancidity.",
                summaryHindi = "द्रव्यमान संरक्षण के नियम हेतु रासायनिक समीकरण संतुलित करना। संयोजन, वियोजन, विस्थापन, द्विविस्थापन एवं रेडॉक्स अभिक्रियाएं। संक्षारण व विकृतगंधिता।",
                summaryEnglish = "Balancing chemical equations, types of reactions, oxidation-reduction, corrosion and rancidity prevention.",
                ncertReference = "NCERT Class 10 Science Chapter 1"
            ),
            ChapterEntity(
                id = "sci_ch2",
                subjectId = "science",
                chapterNumber = 2,
                titleEnglish = "Acids, Bases & Salts",
                titleHindi = "अम्ल, क्षारक एवं लवण",
                subCategory = "Chemistry",
                isIncludedInMpBoard = true,
                orderIndex = 202,
                summaryHinglish = "Acids produce H⁺ ions, bases produce OH⁻ ions. pH scale (0 to 14). Neutralization: Acid + Base -> Salt + Water. Salts: Bleaching powder (CaOCl₂), Baking soda (NaHCO₃), Washing soda (Na₂CO₃·10H₂O), POP (CaSO₄·½H₂O).",
                summaryHindi = "अम्ल (H⁺ आयन) व क्षारक (OH⁻ आयन)। pH पैमाना। उदासीनीकरण अभिक्रिया। विरंजक चूर्ण, बेकिंग सोडा, धावन सोडा, प्लास्टर ऑफ पेरिस।",
                summaryEnglish = "Properties of acids and bases, pH indicators, neutralization, and preparation of important chemical salts.",
                ncertReference = "NCERT Class 10 Science Chapter 2"
            ),
            ChapterEntity(
                id = "sci_ch3",
                subjectId = "science",
                chapterNumber = 3,
                titleEnglish = "Metals & Non-metals",
                titleHindi = "धातु एवं अधातु",
                subCategory = "Chemistry",
                isIncludedInMpBoard = true,
                orderIndex = 203,
                summaryHinglish = "Malleability, ductility, conductivity. Reactivity series (K > Na > Ca > Mg > Al > Zn > Fe > Pb > H > Cu > Ag > Au). Ionic compounds formation and properties (high melting point, conduct electricity in solution).",
                summaryHindi = "धातुओं के भौतिक व रासायनिक गुण। सक्रियता श्रेणी। आयनिक यौगिकों का निर्माण व उच्च गलनांक गुणधर्म।",
                summaryEnglish = "Physical and chemical properties of metals, reactivity series, formation of ionic compounds.",
                ncertReference = "NCERT Class 10 Science Chapter 3"
            ),
            ChapterEntity(
                id = "sci_ch4",
                subjectId = "science",
                chapterNumber = 4,
                titleEnglish = "Carbon & its Compounds",
                titleHindi = "कार्बन एवं उसके यौगिक",
                subCategory = "Chemistry",
                isIncludedInMpBoard = true,
                orderIndex = 204,
                summaryHinglish = "Covalent bonding in carbon (tetravalency & catenation). Saturated (Alkanes CnH2n+2) vs Unsaturated (Alkenes CnH2n, Alkynes CnH2n-2). Functional groups: alcohol (-OH), aldehyde (-CHO), ketone (-CO-), carboxylic acid (-COOH).",
                summaryHindi = "कार्बन की सहसंयोजी प्रकृति, शृंखलन व चतुःसंयोजकता। संतृप्त व असंतृप्त हाइड्रोकार्बन। प्रकार्यात्मक समूह।",
                summaryEnglish = "Tetravalent carbon, covalent bonds, homologous series, functional groups and nomenclature.",
                ncertReference = "NCERT Class 10 Science Chapter 4"
            ),
            ChapterEntity(
                id = "sci_ch5",
                subjectId = "science",
                chapterNumber = 5,
                titleEnglish = "Life Processes",
                titleHindi = "जैव प्रक्रम",
                subCategory = "Biology",
                isIncludedInMpBoard = true,
                orderIndex = 205,
                summaryHinglish = "Autotrophic nutrition (Photosynthesis 6CO₂ + 12H₂O -> C₆H₁₂O₆ + 6O₂ + 6H₂O), Human digestive system, Respiration (Aerobic in mitochondria vs Anaerobic in cytoplasm/yeast), Human Heart (double circulation), Excretion in human (Nephron unit).",
                summaryHindi = "प्रकाश संश्लेषण समीकरण, मानव पाचन तंत्र, श्वसन (वायवीय व अवायवीय), मानव हृदय में दोहरा परिसंचरण, वृक्काणु (नेफ्रॉन) द्वारा उत्सर्जन।",
                summaryEnglish = "Nutrition, aerobic/anaerobic respiration, double circulation in human heart, nephron function in kidneys.",
                ncertReference = "NCERT Class 10 Science Chapter 5"
            ),
            ChapterEntity(
                id = "sci_ch6",
                subjectId = "science",
                chapterNumber = 6,
                titleEnglish = "Control & Coordination",
                titleHindi = "नियंत्रण एवं समन्वय",
                subCategory = "Biology",
                isIncludedInMpBoard = true,
                orderIndex = 206,
                summaryHinglish = "Neuron structure (cyton, dendrite, axon, synapse). Reflex arc (receptor -> sensory neuron -> spinal cord -> motor neuron -> effector). Human brain (forebrain, midbrain, hindbrain). Plant hormones (Auxin, Gibberellin, Cytokinin, Abscisic acid).",
                summaryHindi = "तंत्रिका कोशिका (न्यूरॉन), प्रतिवर्ती चाप, मानव मस्तिष्क के भाग, पादप हार्मोन (ऑक्सिन, जिबरेलिन, साइटोकाइनिन, एब्सिसिक अम्ल)।",
                summaryEnglish = "Nervous system, neuron, reflex arc, human brain functions and plant hormones.",
                ncertReference = "NCERT Class 10 Science Chapter 6"
            ),
            ChapterEntity(
                id = "sci_ch7",
                subjectId = "science",
                chapterNumber = 7,
                titleEnglish = "Light - Reflection & Refraction",
                titleHindi = "प्रकाश - परावर्तन तथा अपवर्तन",
                subCategory = "Physics",
                isIncludedInMpBoard = true,
                orderIndex = 207,
                summaryHinglish = "Laws of reflection. Concave & convex mirrors: Mirror formula 1/f = 1/v + 1/u, magnification m = -v/u = h'/h. Refraction & Snell's Law (sin i / sin r = n). Lens formula 1/f = 1/v - 1/u, power of lens P = 1/f(in m) in Dioptre (D).",
                summaryHindi = "दर्पण सूत्र 1/f = 1/v + 1/u। लेंस सूत्र 1/f = 1/v - 1/u। स्नेल का नियम। लेंस की क्षमता P = 1/f (डायऑप्टर)। किरण आरेख।",
                summaryEnglish = "Reflection by spherical mirrors, refraction, Snell's law, mirror & lens formulas, lens power.",
                ncertReference = "NCERT Class 10 Science Chapter 9"
            ),
            ChapterEntity(
                id = "sci_ch8",
                subjectId = "science",
                chapterNumber = 8,
                titleEnglish = "Human Eye & Colourful World",
                titleHindi = "मानव नेत्र तथा रंगबिरंगा संसार",
                subCategory = "Physics",
                isIncludedInMpBoard = true,
                orderIndex = 208,
                summaryHinglish = "Eye parts: Cornea, pupil, iris, crystalline lens, retina, ciliary muscles (power of accommodation). Defects: Myopia (near-sightedness, corrected by concave lens), Hypermetropia (far-sightedness, convex lens). Dispersion through prism (VIBGYOR), Atmospheric refraction (twinkling of stars), Tyndall effect.",
                summaryHindi = "मानव नेत्र की संरचना, समंजन क्षमता। दृष्टि दोष: निकट दृष्टि (अवतल लेंस) व दूर दृष्टि (उत्तल लेंस)। प्रिज्म से वर्ण-विक्षेपण, तारों का टिमटिमाना।",
                summaryEnglish = "Human eye structure, myopia and hypermetropia correction, prism dispersion and scattering of light.",
                ncertReference = "NCERT Class 10 Science Chapter 10"
            ),
            ChapterEntity(
                id = "sci_ch9",
                subjectId = "science",
                chapterNumber = 9,
                titleEnglish = "Electricity",
                titleHindi = "विद्युत",
                subCategory = "Physics",
                isIncludedInMpBoard = true,
                orderIndex = 209,
                summaryHinglish = "Current I = Q/t (Ampere), Potential difference V = W/Q (Volt). Ohm's Law: V = IR. Resistance factors: R = ρ (l/A). Series: Rs = R1 + R2 + R3. Parallel: 1/Rp = 1/R1 + 1/R2 + 1/R3. Heating effect H = I²Rt (Joule's law). Power P = VI = I²R = V²/R.",
                summaryHindi = "ओम का नियम V = IR। प्रतिरोध का संयोजन (श्रेणीक्रम व समांतर क्रम)। जूल का तापन नियम H = I²Rt। विद्युत शक्ति P = VI।",
                summaryEnglish = "Ohm's law, series and parallel resistor circuits, Joule's law of heating, and electrical power.",
                ncertReference = "NCERT Class 10 Science Chapter 11"
            ),
            ChapterEntity(
                id = "sci_ch10",
                subjectId = "science",
                chapterNumber = 10,
                titleEnglish = "Magnetic Effects of Electric Current",
                titleHindi = "विद्युत धारा के चुंबकीय प्रभाव",
                subCategory = "Physics",
                isIncludedInMpBoard = true,
                orderIndex = 210,
                summaryHinglish = "Magnetic field lines: loops emerge from North and enter South pole. Right Hand Thumb Rule for straight conductor. Solenoid field is uniform inside. Fleming's Left Hand Rule (Thumb-Motion/Force, Forefinger-Field, Middle-Current). Domestic electric circuit: Live (220V), Neutral, Earth wire safety.",
                summaryHindi = "चुंबकीय क्षेत्र रेखाएँ, दक्षिण-हस्त अंगुष्ठ नियम, परिनालिका, फ्लेमिंग का वामहस्त नियम, घरेलू विद्युत परिपथ एवं भू-सम्पर्क तार की महत्ता।",
                summaryEnglish = "Magnetic fields, field lines around conductor and solenoid, Fleming's left hand rule, and domestic circuits.",
                ncertReference = "NCERT Class 10 Science Chapter 12"
            ),
            ChapterEntity(
                id = "sci_ch11",
                subjectId = "science",
                chapterNumber = 11,
                titleEnglish = "Our Environment",
                titleHindi = "हमारा पर्यावरण",
                subCategory = "Biology",
                isIncludedInMpBoard = true,
                orderIndex = 211,
                summaryHinglish = "Biotic and Abiotic components. Food chain and food web. 10% law of energy transfer (Lindeman). Biological magnification: accumulation of non-biodegradable pesticides at top trophic levels. Ozone (O₃) layer depletion by CFCs. Waste management.",
                summaryHindi = "पारितंत्र, खाद्य श्रृंखला, ऊर्जा प्रवाह का 10% नियम, जैव आवर्धन (कीटनाशकों का संचय), ओजोन परत का क्षरण (CFCs) एवं कचरा प्रबंधन।",
                summaryEnglish = "Ecosystem, trophic levels, 10% energy law, biomagnification, ozone depletion and eco-friendly waste management.",
                ncertReference = "NCERT Class 10 Science Chapter 13"
            ),

            // SOCIAL SCIENCE (MP Board Class 10)
            ChapterEntity(
                id = "sst_ch1",
                subjectId = "sst",
                chapterNumber = 1,
                titleEnglish = "The Rise of Nationalism in Europe",
                titleHindi = "यूरोप में राष्ट्रवाद का उदय",
                subCategory = "History",
                isIncludedInMpBoard = true,
                orderIndex = 301,
                summaryHinglish = "French Revolution 1789 introduced ideas of la patrie and le citoyen. Napoleonic Code 1804 abolished privileges based on birth. Unification of Italy (Mazzini, Garibaldi, Cavour, King Victor Emmanuel II) and Germany (Otto von Bismarck, 1871).",
                summaryHindi = "फ्रांसीसी क्रांति (1789), नेपोलियन की नागरिक संहिता (1804), इटली का एकीकरण (मेत्सिनी, गैरीबाल्डी, कावूर) एवं जर्मनी का एकीकरण (बिस्मार्क, 1871)।",
                summaryEnglish = "French Revolution impact, Civil Code 1804, Romanticism, and unifications of Italy and Germany.",
                ncertReference = "NCERT Class 10 History Chapter 1"
            ),
            ChapterEntity(
                id = "sst_ch2",
                subjectId = "sst",
                chapterNumber = 2,
                titleEnglish = "Nationalism in India",
                titleHindi = "भारत में राष्ट्रवाद",
                subCategory = "History",
                isIncludedInMpBoard = true,
                orderIndex = 302,
                summaryHinglish = "Mahatma Gandhi's Satyagraha (Champaran 1917, Kheda 1917, Ahmedabad 1918). Rowlatt Act 1919 and Jallianwala Bagh massacre (13 April 1919). Non-Cooperation Khilafat Movement (1920-1922, called off after Chauri Chaura). Civil Disobedience Movement (1930 Salt March from Sabarmati to Dandi).",
                summaryHindi = "गांधीजी का सत्याग्रह, रॉलेट एक्ट, जलियांवाला बाग हत्याकांड (13 अप्रैल 1919), असहयोग आंदोलन व चौरी-चौरा कांड, दांडी यात्रा व सविनय अवज्ञा आंदोलन (1930)।",
                summaryEnglish = "First World War impact, Satyagraha, Jallianwala Bagh, Non-Cooperation Movement, and Salt Satyagraha.",
                ncertReference = "NCERT Class 10 History Chapter 2"
            ),
            ChapterEntity(
                id = "sst_ch3",
                subjectId = "sst",
                chapterNumber = 3,
                titleEnglish = "Resources & Development",
                titleHindi = "संसाधन एवं विकास",
                subCategory = "Geography",
                isIncludedInMpBoard = true,
                orderIndex = 303,
                summaryHinglish = "Classification of resources (renewable/non-renewable, individual/community/national/international). Resource planning in India. Soil types in India: Alluvial soil (most fertile, northern plains), Black soil (regur, ideal for cotton, MP/Maharashtra), Red & Yellow soil, Laterite soil.",
                summaryHindi = "संसाधनों का वर्गीकरण एवं नियोजन। भारत में मृदा के प्रकार: जलोढ़ मृदा (सर्वाधिक उपजाऊ), काली मृदा (रेगुर मृदा, कपास हेतु उपयुक्त), लाल-पीली व लैटेराइट मृदा।",
                summaryEnglish = "Resource types, sustainable development, resource conservation, and major soil distributions in India.",
                ncertReference = "NCERT Class 10 Geography Chapter 1"
            ),
            ChapterEntity(
                id = "sst_ch4",
                subjectId = "sst",
                chapterNumber = 4,
                titleEnglish = "Power Sharing & Federalism",
                titleHindi = "सत्ता की साझेदारी एवं संघवाद",
                subCategory = "Civics",
                isIncludedInMpBoard = true,
                orderIndex = 304,
                summaryHinglish = "Power sharing prevents conflict (Belgium accommodation vs Sri Lanka majoritarianism). Forms: Horizontal (Legislature, Executive, Judiciary) and Vertical (Central, State, Local). Federalism in India: Union List, State List, Concurrent List. 73rd and 74th Amendments for Panchayati Raj decentralization.",
                summaryHindi = "बेल्जियम और श्रीलंका में सत्ता की साझेदारी का मॉडल। संघवाद के प्रमुख लक्षण: संघ सूची, राज्य सूची, समवर्ती सूची। 1992 का विकेंद्रीकरण और पंचायती राज।",
                summaryEnglish = "Power sharing mechanisms, federal features of Indian Constitution, Union/State/Concurrent lists, and 1992 decentralization.",
                ncertReference = "NCERT Class 10 Civics Chapters 1 & 2"
            ),
            ChapterEntity(
                id = "sst_ch5",
                subjectId = "sst",
                chapterNumber = 5,
                titleEnglish = "Sectors of the Indian Economy",
                titleHindi = "भारतीय अर्थव्यवस्था के क्षेत्रक",
                subCategory = "Economics",
                isIncludedInMpBoard = true,
                orderIndex = 305,
                summaryHinglish = "Three sectors: Primary (Agriculture, forestry), Secondary (Manufacturing, industry), Tertiary (Services: banking, transport, IT). Disguised unemployment in agriculture. Organised vs Unorganised sectors. Public vs Private sectors. MGNREGA 2005 (100 days guaranteed employment).",
                summaryHindi = "प्राथमिक, द्वितीयक एवं तृतीयक क्षेत्रक। प्रच्छन्न (छिपी हुई) बेरोजगारी। संगठित व असंगठित क्षेत्र। मनरेगा 2005 (100 दिनों का सुनिश्चित रोजगार)।",
                summaryEnglish = "Primary, secondary, and tertiary sectors, employment patterns, disguised unemployment, and MGNREGA guarantee.",
                ncertReference = "NCERT Class 10 Economics Chapter 2"
            ),

            // ENGLISH (MP Board Class 10)
            ChapterEntity(
                id = "eng_ch1",
                subjectId = "english",
                chapterNumber = 1,
                titleEnglish = "A Letter to God (First Flight)",
                titleHindi = "ए लेटर टू गॉड (ईश्वर के नाम पत्र)",
                subCategory = "Literature",
                isIncludedInMpBoard = true,
                orderIndex = 401,
                summaryHinglish = "Written by G.L. Fuentes. Lencho, a hard-working farmer, loses his ripe corn crop to a destructive hailstorm. With supreme faith in God, he writes a letter asking for 100 pesos. The kind postmaster collects 70 pesos to help him, but Lencho suspects the post office employees to be a 'bunch of crooks'. Theme of innocent faith and ironical human nature.",
                summaryHindi = "जी.एल. फ्यूएंट्स द्वारा लिखित। लेन्चो एक मेहनती किसान है जिसकी मक्के की फसल ओलों से बर्बाद हो जाती है। अटूट विश्वास से वह ईश्वर को 100 पेसोस के लिए पत्र लिखता है। पोस्टमास्टर 70 पेसोस एकत्र कर भेजता है, पर लेन्चो डाक कर्मचारियों पर ही शक करता है।",
                summaryEnglish = "Story of Lencho's unwavering faith in God, the postmaster's benevolence, and the irony of human suspicion.",
                ncertReference = "First Flight Chapter 1"
            ),
            ChapterEntity(
                id = "eng_ch2",
                subjectId = "english",
                chapterNumber = 2,
                titleEnglish = "Nelson Mandela: Long Walk to Freedom",
                titleHindi = "नेल्सन मंडेला: लॉन्ग वॉक टू फ्रीडम",
                subCategory = "Literature",
                isIncludedInMpBoard = true,
                orderIndex = 402,
                summaryHinglish = "Extract from autobiography. 10th May 1994, inauguration of South Africa's first democratic non-racial government at Union Buildings, Pretoria. Mandela speaks about the end of Apartheid, courage being the triumph over fear, and twin obligations: towards family and towards nation.",
                summaryHindi = "नेल्सन मंडेला की आत्मकथा। 10 मई 1994 को रंगभेद नीति (Apartheid) की समाप्ति व लोकतंत्र की स्थापना। साहस का अर्थ भय की अनुपस्थिति नहीं, बल्कि उस पर विजय पाना है।",
                summaryEnglish = "Mandela's reflection on freedom, overcoming fear, the struggle against apartheid, and moral obligations.",
                ncertReference = "First Flight Chapter 2"
            ),
            ChapterEntity(
                id = "eng_ch3",
                subjectId = "english",
                chapterNumber = 3,
                titleEnglish = "Dust of Snow & Fire and Ice (Robert Frost)",
                titleHindi = "डस्ट ऑफ स्नो एवं फायर एंड आइस",
                subCategory = "Poetry",
                isIncludedInMpBoard = true,
                orderIndex = 403,
                summaryHinglish = "Dust of Snow: A crow shakes down snow from a poisonous hemlock tree on poet, transforming his melancholic mood into positive energy (nature heals). Fire and Ice: Fire symbolizes uncontrolled human desire/greed, Ice symbolizes cold hatred/rigidity; both are potent enough to destroy the world.",
                summaryHindi = "रॉबर्ट फ्रॉस्ट की कविताएं। 'डस्ट ऑफ स्नो' में प्रकृति के तुच्छ से दिखने वाले तत्व भी मन का अवसाद मिटा देते हैं। 'फायर एंड आइस' में आग (वासना/लोभ) और बर्फ (घृणा) दोनों संसार को नष्ट करने के लिए पर्याप्त हैं।",
                summaryEnglish = "Symbolism of small natural moments in uplifting human spirits, and destructive forces of human greed vs cold hatred.",
                ncertReference = "First Flight Poems 1 & 2"
            ),
            ChapterEntity(
                id = "eng_ch4",
                subjectId = "english",
                chapterNumber = 4,
                titleEnglish = "English Grammar & MP Board Writing",
                titleHindi = "अंग्रेजी व्याकरण एवं लेखन",
                subCategory = "Grammar & Writing",
                isIncludedInMpBoard = true,
                orderIndex = 404,
                summaryHinglish = "Class 10 MP Board Grammar: Tenses, Modals (can, could, should, must), Active & Passive Voice, Determiners (some, any, much, many, each, every), Conjunctions (as soon as, so...that). Formal letters (to Principal/Collector) and Picture Guided Composition.",
                summaryHindi = "कक्षा 10 एमपी बोर्ड व्याकरण: काल, मॉडल्स, वाच्य, डिटरमाइनर्स तथा औपचारिक पत्र एवं निबंध लेखन प्रारूप।",
                summaryEnglish = "Essential MP Board Class 10 grammar rules, active/passive voice transformation, and official letter formats.",
                ncertReference = "MP Board English Grammar"
            ),

            // HINDI (MP Board Class 10)
            ChapterEntity(
                id = "hin_ch1",
                subjectId = "hindi",
                chapterNumber = 1,
                titleEnglish = "Surdas ke Pad (Kshitij)",
                titleHindi = "सूरदास के पद (क्षितिज भाग-2)",
                subCategory = "काव्य खंड",
                isIncludedInMpBoard = true,
                orderIndex = 501,
                summaryHinglish = "B भ्रमरगीत प्रसंग से उद्धृत। उद्धव गोपियों को ज्ञान और योग का संदेश देते हैं। गोपियाँ व्यंग्य करती हैं कि उद्धव कमल के पत्ते की तरह हैं जो जल में रहकर भी गीला नहीं होता। वे योग को 'कड़वी ककड़ी' जैसा निरर्थक बताती हैं और एकनिष्ठ कृष्ण प्रेम को प्रकट करती हैं।",
                summaryHindi = "सूरदास के भ्रमरगीत से संकलित पद। उद्धव के योग संदेश पर गोपियों का वाक्चातुर्य व व्यंग्य। गोपियाँ कृष्ण के प्रति अनन्य प्रेम व्यक्त करती हैं और राजधर्म की याद दिलाती हैं।",
                summaryEnglish = "Surdas's Bhramargeet: Gopis refute Uddhav's dry intellectual yoga knowledge with pure spontaneous love for Krishna.",
                ncertReference = "क्षितिज भाग-2 अध्याय 1"
            ),
            ChapterEntity(
                id = "hin_ch2",
                subjectId = "hindi",
                chapterNumber = 2,
                titleEnglish = "Ram-Lakshman-Parshuram Samvad",
                titleHindi = "राम-लक्ष्मण-परशुराम संवाद (तुलसीदास)",
                subCategory = "काव्य खंड",
                isIncludedInMpBoard = true,
                orderIndex = 502,
                summaryHinglish = "रामचरितमानस के बालकांड से लिया गया। सीता स्वयंवर में शिव धनुष टूटने पर परशुराम अत्यंत क्रोधित होते हैं। लक्ष्मण व्यंग्यपूर्ण वचनों से उन्हें उत्तर देते हैं ('इहाँ कुम्हड़बतिआ कोउ नाहीं')। श्री राम विनम्रता और शांत स्वभाव से परशुराम के क्रोध को शांत करते हैं। वीर रस और रौद्र रस का सुंदर उदाहरण।",
                summaryHindi = "तुलसीदास रचित बालकांड प्रसंग। शिव धनुष भंजन पर परशुराम का क्रोध, लक्ष्मण के तीखे व्यंग्य बाण तथा श्री राम का शीतल और संयमित आचरण। चौपाई व दोहा छंद का प्रयोग।",
                summaryEnglish = "Dialogue from Ramcharitmanas between furious Parashurama, witty Lakshmana, and humble Rama upon breaking of Shiva's bow.",
                ncertReference = "क्षितिज भाग-2 अध्याय 2"
            ),
            ChapterEntity(
                id = "hin_ch3",
                subjectId = "hindi",
                chapterNumber = 3,
                titleEnglish = "Netaji ka Chashma (Swayam Prakash)",
                titleHindi = "नेताजी का चश्मा (स्वयं प्रकाश)",
                subCategory = "गद्य खंड",
                isIncludedInMpBoard = true,
                orderIndex = 503,
                summaryHinglish = "हालदार साहब हर पंद्रहवें दिन कस्बे से गुजरते थे जहाँ नेताजी सुभाष चंद्र बोस की संगमरमर की मूर्ति पर असली चश्मा बदलता रहता था। यह चश्मा कैप्टन चश्मेवाला लगाता था। कैप्टन की मृत्यु के बाद बच्चों द्वारा सरकंडे का चश्मा लगाया जाना यह साबित करता है कि देशभक्ति केवल सैनिकों में नहीं, हर नागरिक और नई पीढ़ी में जीवित है।",
                summaryHindi = "हालदार साहब और कैप्टन चश्मेवाले की प्रेरक कहानी। नेताजी की मूर्ति पर सरकंडे का चश्मा देखकर हालदार साहब भावुक हो जाते हैं। कहानी सिखाती है कि देशभक्ति मन की भावना है।",
                summaryEnglish = "Touching story highlighting ordinary citizens' patriotism through Captain spectacles-seller honoring Subhash Chandra Bose.",
                ncertReference = "क्षितिज भाग-2 अध्याय 10"
            ),
            ChapterEntity(
                id = "hin_ch4",
                subjectId = "hindi",
                chapterNumber = 4,
                titleEnglish = "Hindi Vyakaran (Ras, Chhand, Alankar)",
                titleHindi = "हिंदी व्याकरण (रस, छंद, अलंकार)",
                subCategory = "व्याकरण",
                isIncludedInMpBoard = true,
                orderIndex = 504,
                summaryHinglish = "MP Board Important Grammar: 1. रस के चार अंग (स्थायी भाव, विभाव, अनुभाव, संचारी भाव) व 10 रस (शृंगार, हास्य, करुण, वीर, रौद्र, भयानक, बीभत्स, अद्भुत, शांत, वात्सल्य)। 2. छंद: दोहा (13+11) व चौपाई (16 मात्राएं)। 3. अलंकार: अनुप्रास, रूपक, उपमा, उत्प्रेक्षा, अतिशयोक्ति। 4. संधि व समास भेद।",
                summaryHindi = "कक्षा 10 अनिवार्य व्याकरण: रस की परिभाषा व अंग, प्रमुख स्थायी भाव, दोहा-चौपाई छंद की मात्रा गणना, प्रमुख अलंकार (अनुप्रास, उपमा, रूपक, उत्प्रेक्षा) तथा समास के भेद।",
                summaryEnglish = "Core MP Board Hindi grammar rules: 10 Ras and Sthayi Bhav, Doha and Chaupai Chhand metrics, and key Alankars.",
                ncertReference = "MP Board Hindi Vyakaran"
            ),

            // SANSKRIT (MP Board Class 10)
            ChapterEntity(
                id = "san_ch1",
                subjectId = "sanskrit",
                chapterNumber = 1,
                titleEnglish = "Shuchiparyavaranam (Shemushi)",
                titleHindi = "शुचिपर्यावरणम् (शेमुषी भाग-2)",
                subCategory = "पद्य",
                isIncludedInMpBoard = true,
                orderIndex = 601,
                summaryHinglish = "प्रो. हरिदत्त शर्मा विरचित 'लसल्लतिका' काव्यसंग्रह से उद्धृत। महानगरों में बढ़ते प्रदूषण, लोहे के चक्र और विषैले धुएँ से परेशान होकर कवि शुद्ध पर्यावरण ('शुचि पर्यावरणम्') की शरण में जाने का आह्वान करते हैं। ग्रामान्ते निर्झर-नदी-पयःपूरम् का सुख प्रकृति की गोद में ही संभव है।",
                summaryHindi = "महानगरों के वायु, जल और ध्वनि प्रदूषण से त्रस्त कवि प्रकृति की शुद्ध शरण में जाने की प्रार्थना करते हैं। पर्यावरण संरक्षण का सार्वकालिक संदेश।",
                summaryEnglish = "Hymn to clean environment (Shuchi Paryavaranam) advocating return to pristine nature amidst modern urban pollution.",
                ncertReference = "शेमुषी भाग-2 प्रथमः पाठः"
            ),
            ChapterEntity(
                id = "san_ch2",
                subjectId = "sanskrit",
                chapterNumber = 2,
                titleEnglish = "Buddhirbalavati Sada (Shemushi)",
                titleHindi = "बुद्धिर्बलवती सदा (शेमुषी भाग-2)",
                subCategory = "गद्य/कथा",
                isIncludedInMpBoard = true,
                orderIndex = 602,
                summaryHinglish = "शुकसप्तति कथाग्रंथ से संपादित। बुद्धिमती नामक स्त्री अपने दो पुत्रों के साथ घने जंगल में जा रही थी तभी सामने बाघ आ जाता है। वह घबराने के बजाय अपनी तीक्ष्ण बुद्धि से दोनों पुत्रों को डांटती है कि 'एक ही बाघ के लिए क्यों लड़ रहे हो, इसे बांटकर खाओ'। बाघ डरकर भाग जाता है। सीख: बुद्धि हमेशा बल से श्रेष्ठ होती है।",
                summaryHindi = "बुद्धिमती स्त्री की बुद्धिमत्ता की रोचक कथा। बुद्धि के बल पर उसने भयानक व्याघ्र (बाघ) और शृगाल को भी परास्त कर दिया। सर्वदा बुद्धि ही बलवान होती है।",
                summaryEnglish = "Story proving that presence of mind and intellect (Buddhi) always triumph over brute physical force (Bala).",
                ncertReference = "शेमुषी भाग-2 द्वितीयः पाठः"
            ),
            ChapterEntity(
                id = "san_ch3",
                subjectId = "sanskrit",
                chapterNumber = 3,
                titleEnglish = "Sanskrit Vyakaran (Sandhi, Samas, Dhatu)",
                titleHindi = "संस्कृत व्याकरण (सन्धि, समास, रूप)",
                subCategory = "व्याकरण",
                isIncludedInMpBoard = true,
                orderIndex = 603,
                summaryHinglish = "1. सन्धि: व्यंजन सन्धि (श्चुत्व, जश्त्व), विसर्ग सन्धि (उत्व, रुत्व, विसर्ग लोप)। 2. समास: तत्पुरुष, कर्मधारय, द्विगु, द्वन्द्व, बहुव्रीहि, अव्ययीभाव। 3. शब्द रूप: बालक, लता, फल, अस्मद् (अहम्-आवाम्-वयम्), युष्मद् (त्वम्-युवाम्-यूयम्)। 4. धातु रूप: पठ्, गम्, भू, दृश् 5 लकारों में (लट्, लृट्, लङ्, लोट्, विधिलिङ्)। प्रत्यय: क्त्वा, ल्यप्, तुमुन्, क्त, क्तवतु।",
                summaryHindi = "एमपी बोर्ड परीक्षा हेतु महत्वपूर्ण संस्कृत व्याकरण: व्यंजन व विसर्ग संधि के नियम, समास विग्रह, कारक-विभक्ति नियम, सर्वनाम शब्द रूप तथा मुख्य धातुओं के 5 लकारों में रूप।",
                summaryEnglish = "Key Sanskrit grammar topics for Class 10: Sandhi, Samas, Shabda Rupa, Dhatu Rupa across 5 Lakaras, and Pratyayas.",
                ncertReference = "MP Board Sanskrit Vyakaran"
            )
        )
    }
}
